version: '3'
services:
  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000" to use without nginx
      
    env_file:
      - ./.env

    volumes:
      - .:/app
      - /app/node_modules
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # To use http 
      - "443:443" # To use https
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mvc