version: '3'
services:
  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://root:root@cluster0.c2lbl.mongodb.net/?retryWrites=true&w=majority

    volumes:
      - .:/app